language: scala
sudo: false
jdk: oraclejdk8
scala:
    - 2.10.7
    - 2.11.12
    - 2.12.4
    - 2.13.0-M3

matrix:
  include:
  - env: SCALA_NATIVE
    sudo: required
    scala: 2.11.12
    dist: trusty
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/9069e8d447f7a9/bin/travis_setup.sh | bash -x
    script:
    - sbt lensesNative/test "show lensesNative/nativeMissingDependencies"
