name: Release

on:
  push:
    branches: [master]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Ruby caches
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('.travis/push_website.sh') }}
        restore-keys: |
            ${{ runner.os }}-gems-
    - name: Scala caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-docs-${{ hashFiles('**/*.sbt') }}
    - uses: actions/setup-java@v1
      with:
        java-version: 12
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: update-docs
      run: |
        git config --global user.name "ScalaPB Docs"
        git config --global user.email "scalapb-updater@users.noreply.github.com"
        eval "$(ssh-agent -s)"
        echo "$TOKEN" | ssh-add -
        .travis/push_website.sh
      env:
          TOKEN: ${{secrets.DEPLOY_KEY}}
    - uses: olafurpg/setup-gpg@v2
    - name: Publish ${{ github.ref }}
      run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  native:
    name: Create native image for ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: graalvm@20.1
    - run: |
        gu install native-image
        ./make_reflect_config.sh
        sbt protocGenScalaUnix/graalvm-native-image:packageBin
        zip -j image.zip protocGenScalaUnix/target/graalvm-native-image/protoc-gen-scala

