name: Release

on:
  push:
    branches: [master]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 12
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: update-docs
      run: |
        .travis/push_website.sh
