name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCALA_VERSION: ${{matrix.scala}}
    strategy:
      matrix:
        scala: [2_12, 2_13, 3]
        script: [mima, e2e, proptest]
        include:
        - scala: 2_12
          script: examples_and_formatting

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin

    - name: Mount caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{matrix.scala}}-${{matrix.script}}-${{ hashFiles('**/*.sbt') }}

    - name: ${{matrix.script}}
      run: |
        ./${{matrix.script}}.sh
      env:
        JAVA_OPTS: -Xmx4G -XX:+UseG1GC
        JVM_OPTS:  -Xmx4G -XX:+UseG1GC

  conformance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.cache/bazel
          ~/.ivy2/cache
          ~/.cache/coursier
        key: bazel
    - run: |
        export PROTOBUF_VERSION=3.19.6
        export USE_BAZEL_VERSION=3.7.2
        curl -L https://github.com/protocolbuffers/protobuf/archive/refs/tags/v${PROTOBUF_VERSION}.zip -o /tmp/protobuf.zip
        unzip /tmp/protobuf.zip
        cd protobuf-${PROTOBUF_VERSION}
        bazel build conformance_test_runner
        cd ..
        sbt conformanceJVM2_13/assembly
        protobuf-${PROTOBUF_VERSION}/bazel-bin/conformance_test_runner --enforce_recommended \
          --failure_list conformance/failure_list_scalapb.txt \
          --text_format_failure_list conformance/text_format_failure_list_scalapb.txt \
          conformance/target/jvm-2.13/conformance

      shell: bash

  # Single final job for mergify.
  ci-passed:
    runs-on: ubuntu-latest
    needs: [build, conformance]
    steps:
    - run: ':'
